// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
	require('../src/components/Channel/ChannelFunds/ChannelFunds.stories');
	require('../src/components/Channel/ChannelHeader/ChannelHeader.stories');
	require('../src/components/Channel/ChannelLogin/ChannelLogin.stories');
	require('../src/components/Channel/ChannelProfile/ChannelProfile.stories');
	require('../src/components/Channel/ChannelSelf/ChannelSelf.stories');
	require('../src/components/Channel/ChannelSelfs/ChannelSelfs.stories');
	require('../src/components/Channel/FollowChannel/FollowChannel.stories');
	require('../src/components/Channel/RegisterChannel/RegisterChannel.stories');
	require('../src/components/Channel/UpdateChannel/UpdateChannel.stories');
	require('../src/components/ChannelProfileFeed/ChannelProfileFeed.stories');
	require('../src/components/ChannelSelfFeed/ChannelSelfFeed.stories');
	require('../src/components/CreditTransaction/CreditTransactions/CreditTransactions.stories');
	require('../src/components/HomeFeed/HomeFeed.stories');
	require('../src/components/Login/Login.stories');
	require('../src/components/Notification/NotificationListItem/NotificationListItem.stories');
	require('../src/components/Notification/Notifications/Notifications.stories');
	require('../src/components/Onboarding/OnboardingWelcome/OnboardingWelcome.stories');
	require('../src/components/Purchase/Products/Products.stories');
	require('../src/components/Register/Register.stories');
	require('../src/components/RequestPasswordReset/RequestPasswordReset.stories');
	require('../src/components/RequestedChannel/RequestedChannels/RequestedChannels.stories');
	require('../src/components/ResetPassword/ResetPassword.stories');
	require('../src/components/Stream/CalculateStreamRevenue/CalculateStreamRevenue.stories');
	require('../src/components/Stream/CameraStream/components/CameraStreamControls/CameraStreamControls.stories');
	require('../src/components/Stream/CancelStream/CancelStream.stories');
	require('../src/components/Stream/CancelStream/components/CancelStreamForm/CancelStreamForm.stories');
	require('../src/components/Stream/ConsumingStreamProfiles/ConsumingStreamProfiles.stories');
	require('../src/components/Stream/CreateUpdateStream/CreateUpdateStream.stories');
	require('../src/components/Stream/CreateUpdateStream/components/StreamStates/StreamStates.stories');
	require('../src/components/Stream/DeleteStream/DeleteStream.stories');
	require('../src/components/Stream/GoLive/GoLive.stories');
	require('../src/components/Stream/PublishStream/PublishStream.stories');
	require('../src/components/Stream/ReportStream/ReportStream.stories');
	require('../src/components/Stream/StreamProfile/StreamProfile.stories');
	require('../src/components/Stream/StreamProfile/components/StreamCommunication/StreamCommunication.stories');
	require('../src/components/Stream/StreamProfile/components/StreamPurchase/StreamPurchase.stories');
	require('../src/components/Stream/StreamSelf/StreamSelf.stories');
	require('../src/components/Stream/StreamSelfListItem/StreamSelfListItem.stories');
	require('../src/components/Stream/StreamSelfs/StreamSelfs.stories');
	require('../src/components/Stream/StreamVideo/StreamVideo.stories');
	require('../src/components/Stream/StreamVideo/components/StreamControls/StreamControls.stories');
	require('../src/components/Stream/UnlistStream/UnlistStream.stories');
	require('../src/components/StreamComment/CreateStreamComment/CreateStreamComment.stories');
	require('../src/components/StreamComment/StreamCommentListItem/StreamCommentListItem.stories');
	require('../src/components/StreamComment/StreamComments/StreamComments.stories');
	require('../src/components/StreamMessage/CreateStreamMessage/CreateStreamMessage.stories');
	require('../src/components/StreamMessage/StreamMessageListItem/StreamMessageListItem.stories');
	require('../src/components/StreamMessage/StreamMessages/StreamMessages.stories');
	require('../src/components/StreamMessage/StreamMessagesVod/StreamMessagesVod.stories');
	require('../src/components/UI/Button/Button.stories');
	require('../src/components/UI/Cards/ChannelCard/ChannelCard.stories');
	require('../src/components/UI/Cards/CreditTransactionCard/CreditTransactionCard.stories');
	require('../src/components/UI/Cards/StreamCard/StreamCard.stories');
	require('../src/components/UI/Cards/WalletCard/WalletCard.stories');
	require('../src/components/UI/Chip/Chip.stories');
	require('../src/components/UI/DateTimePicker/components/DateTimePicker/DateTimePicker.stories');
	require('../src/components/UI/DateTimePicker/components/DurationPicker/DurationPicker.stories');
	require('../src/components/UI/Drawer/Drawer.stories');
	require('../src/components/UI/DrawerV2/DrawerV2.stories');
	require('../src/components/UI/Form/components/DateInput/DateInput.stories');
	require('../src/components/UI/Form/components/DurationInput/DurationInput.stories');
	require('../src/components/UI/Form/components/MessageInput/MessageInput.stories');
	require('../src/components/UI/Form/components/SearchInput/SearchInput.stories');
	require('../src/components/UI/Form/components/Switch/Switch.stories');
	require('../src/components/UI/Form/components/TextArea/TextArea.stories');
	require('../src/components/UI/Form/components/TextInput/TextInput.stories');
	require('../src/components/UI/Headers/ChannelSelfHeader/ChannelSelfHeader.stories');
	require('../src/components/UI/Headers/Header/Header.stories');
	require('../src/components/UI/Icon/Icon.stories');
	require('../src/components/UI/LiveConsumers/LiveConsumers.stories');
	require('../src/components/UI/LoadRetry/LoadRetry.stories');
	require('../src/components/UI/LoadingIcon/LoadingIcon.stories');
	require('../src/components/UI/Onboarding/OnboardingPageWrap/OnboardingPageWrap.stories');
	require('../src/components/UI/Permission/PermissionsError.stories');
	require('../src/components/UI/PulsingIcon/PulsingIcon.stories');
	require('../src/components/UI/ShareButton/ShareButton.stories');
	require('../src/components/UI/Slider/Slider.stories');
	require('../src/components/UI/Toast/Toast.stories');
	require('../src/components/UI/Typography/Typography.stories');
	require('../src/components/UserSelf/Profile/Profile.stories');
	require('../src/components/UserSelf/UpdateEmail/UpdateEmail.stories');
	require('../src/components/UserSelf/UpdatePassword/UpdatePassword.stories');
	require('../src/components/UserSelf/UpdateProfilePicture/UpdateProfilePicture.stories');
	require('../src/components/UserSelf/UpdateUsername/UpdateUsername.stories');
	require('../src/components/Wallet/Wallet.stories');
	require('../src/modules/AssetPicker/AssetPicker.stories');
}

const stories = [
	'../src/components/Channel/ChannelFunds/ChannelFunds.stories',
	'../src/components/Channel/ChannelHeader/ChannelHeader.stories',
	'../src/components/Channel/ChannelLogin/ChannelLogin.stories',
	'../src/components/Channel/ChannelProfile/ChannelProfile.stories',
	'../src/components/Channel/ChannelSelf/ChannelSelf.stories',
	'../src/components/Channel/ChannelSelfs/ChannelSelfs.stories',
	'../src/components/Channel/FollowChannel/FollowChannel.stories',
	'../src/components/Channel/RegisterChannel/RegisterChannel.stories',
	'../src/components/Channel/UpdateChannel/UpdateChannel.stories',
	'../src/components/ChannelProfileFeed/ChannelProfileFeed.stories',
	'../src/components/ChannelSelfFeed/ChannelSelfFeed.stories',
	'../src/components/CreditTransaction/CreditTransactions/CreditTransactions.stories',
	'../src/components/HomeFeed/HomeFeed.stories',
	'../src/components/Login/Login.stories',
	'../src/components/Notification/NotificationListItem/NotificationListItem.stories',
	'../src/components/Notification/Notifications/Notifications.stories',
	'../src/components/Onboarding/OnboardingWelcome/OnboardingWelcome.stories',
	'../src/components/Purchase/Products/Products.stories',
	'../src/components/Register/Register.stories',
	'../src/components/RequestPasswordReset/RequestPasswordReset.stories',
	'../src/components/RequestedChannel/RequestedChannels/RequestedChannels.stories',
	'../src/components/ResetPassword/ResetPassword.stories',
	'../src/components/Stream/CalculateStreamRevenue/CalculateStreamRevenue.stories',
	'../src/components/Stream/CameraStream/components/CameraStreamControls/CameraStreamControls.stories',
	'../src/components/Stream/CancelStream/CancelStream.stories',
	'../src/components/Stream/CancelStream/components/CancelStreamForm/CancelStreamForm.stories',
	'../src/components/Stream/ConsumingStreamProfiles/ConsumingStreamProfiles.stories',
	'../src/components/Stream/CreateUpdateStream/CreateUpdateStream.stories',
	'../src/components/Stream/CreateUpdateStream/components/StreamStates/StreamStates.stories',
	'../src/components/Stream/DeleteStream/DeleteStream.stories',
	'../src/components/Stream/GoLive/GoLive.stories',
	'../src/components/Stream/PublishStream/PublishStream.stories',
	'../src/components/Stream/ReportStream/ReportStream.stories',
	'../src/components/Stream/StreamProfile/StreamProfile.stories',
	'../src/components/Stream/StreamProfile/components/StreamCommunication/StreamCommunication.stories',
	'../src/components/Stream/StreamProfile/components/StreamPurchase/StreamPurchase.stories',
	'../src/components/Stream/StreamSelf/StreamSelf.stories',
	'../src/components/Stream/StreamSelfListItem/StreamSelfListItem.stories',
	'../src/components/Stream/StreamSelfs/StreamSelfs.stories',
	'../src/components/Stream/StreamVideo/StreamVideo.stories',
	'../src/components/Stream/StreamVideo/components/StreamControls/StreamControls.stories',
	'../src/components/Stream/UnlistStream/UnlistStream.stories',
	'../src/components/StreamComment/CreateStreamComment/CreateStreamComment.stories',
	'../src/components/StreamComment/StreamCommentListItem/StreamCommentListItem.stories',
	'../src/components/StreamComment/StreamComments/StreamComments.stories',
	'../src/components/StreamMessage/CreateStreamMessage/CreateStreamMessage.stories',
	'../src/components/StreamMessage/StreamMessageListItem/StreamMessageListItem.stories',
	'../src/components/StreamMessage/StreamMessages/StreamMessages.stories',
	'../src/components/StreamMessage/StreamMessagesVod/StreamMessagesVod.stories',
	'../src/components/UI/Button/Button.stories',
	'../src/components/UI/Cards/ChannelCard/ChannelCard.stories',
	'../src/components/UI/Cards/CreditTransactionCard/CreditTransactionCard.stories',
	'../src/components/UI/Cards/StreamCard/StreamCard.stories',
	'../src/components/UI/Cards/WalletCard/WalletCard.stories',
	'../src/components/UI/Chip/Chip.stories',
	'../src/components/UI/DateTimePicker/components/DateTimePicker/DateTimePicker.stories',
	'../src/components/UI/DateTimePicker/components/DurationPicker/DurationPicker.stories',
	'../src/components/UI/Drawer/Drawer.stories',
	'../src/components/UI/DrawerV2/DrawerV2.stories',
	'../src/components/UI/Form/components/DateInput/DateInput.stories',
	'../src/components/UI/Form/components/DurationInput/DurationInput.stories',
	'../src/components/UI/Form/components/MessageInput/MessageInput.stories',
	'../src/components/UI/Form/components/SearchInput/SearchInput.stories',
	'../src/components/UI/Form/components/Switch/Switch.stories',
	'../src/components/UI/Form/components/TextArea/TextArea.stories',
	'../src/components/UI/Form/components/TextInput/TextInput.stories',
	'../src/components/UI/Headers/ChannelSelfHeader/ChannelSelfHeader.stories',
	'../src/components/UI/Headers/Header/Header.stories',
	'../src/components/UI/Icon/Icon.stories',
	'../src/components/UI/LiveConsumers/LiveConsumers.stories',
	'../src/components/UI/LoadRetry/LoadRetry.stories',
	'../src/components/UI/LoadingIcon/LoadingIcon.stories',
	'../src/components/UI/Onboarding/OnboardingPageWrap/OnboardingPageWrap.stories',
	'../src/components/UI/Permission/PermissionsError.stories',
	'../src/components/UI/PulsingIcon/PulsingIcon.stories',
	'../src/components/UI/ShareButton/ShareButton.stories',
	'../src/components/UI/Slider/Slider.stories',
	'../src/components/UI/Toast/Toast.stories',
	'../src/components/UI/Typography/Typography.stories',
	'../src/components/UserSelf/Profile/Profile.stories',
	'../src/components/UserSelf/UpdateEmail/UpdateEmail.stories',
	'../src/components/UserSelf/UpdatePassword/UpdatePassword.stories',
	'../src/components/UserSelf/UpdateProfilePicture/UpdateProfilePicture.stories',
	'../src/components/UserSelf/UpdateUsername/UpdateUsername.stories',
	'../src/components/Wallet/Wallet.stories',
	'../src/modules/AssetPicker/AssetPicker.stories'
];

module.exports = {
  loadStories,
  stories,
};
